InterneStructure_hierarchie:
    pattern:  /hierarchie
    defaults: { _controller: InterneStructureBundle:Structure:hierarchie }

InterneStructure_distinctions:
    pattern:  /distinctions
    defaults: { _controller: InterneStructureBundle:Distinction:distinctions }

InterneStructure_attributions_fonctions:
    pattern:  /attributions-fonctions
    defaults: { _controller: InterneStructureBundle:Attribution:attributionsFonctions }

InterneStructure_voir_groupe:
    pattern:  /groupe/{id}
    defaults: { _controller: InterneStructureBundle:Structure:voirGroupe }
    options:
        expose: true
    
InterneStructure_ajouter_groupe:
    pattern:  /ajouter/groupe
    defaults: { _controller: InterneStructureBundle:Structure:addGroupe }
    
InterneStructure_ajouter_type:
    pattern:  /ajouter/type
    defaults: { _controller: InterneStructureBundle:Structure:addType }

InterneStructure_add_attributions:
    pattern:  /add/attribution/{id}
    defaults: { _controller: InterneStructureBundle:Attribution:addAttributions }
    options:
        expose: true

InterneStructure_remove_attribution:
    pattern:  /remove/attribution/{attributionId}
    defaults: { _controller: InterneStructureBundle:Attribution:removeAttribution }
    
#ajax
InterneStructure_full_hierarchie:
    pattern:  /ajax/full_hierarchie
    defaults: { _controller: InterneStructureBundle:Structure:AJAXGetFullHierarchie }
    options:
        expose: true
  
InterneStructure_attributions_groupes_enfants:
    pattern:  /ajax/attributions_from_groupes/{id}/{hierarchie}/{date1}/{date2}
    defaults: { _controller: InterneStructureBundle:Attribution:AJAXGetAttributionsGroupes }
    options:
        expose: true
        
InterneStructure_attribution_modify:
    pattern:  /ajax/attributions/modify
    defaults: { _controller: InterneStructureBundle:Attribution:AJAXModifyAttribution }
    options:
        expose: true