InterneSearch_search:
    pattern:  /
    defaults: { _controller: InterneSearchBundle:Search:search }

InterneSearch_search_members:
    pattern:  /ajax/search/members
    defaults: { _controller: InterneSearchBundle:Search:searchMembers }
