parameters:
#    interne_search.example.class: Interne\SearchBundle\Example

services:
#    interne_search.example:
#        class: %interne_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
