<?php

namespace Interne\FichierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeniteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeniteurRepository extends EntityRepository
{
}
