<?php

namespace Interne\FichierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    /**
     * la méthode findCurrentAttribution va récupérer l'attribution courante
     * d'un membre, avec une possibilité.
     * Par défaut, la fonction ne renvoie q'un seul résultat
     */
    public function findCurrentAttribution($id, $one = true) {
        
        $membre = $this->find($id);
        
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
           ->from('InterneStructureBundle:Attribution', 'a')
           ->where('a.membre = :membre')
           ->setParameter('membre', $membre)
           ->andWhere('ifNull(DATE(a.dateFin), :farAway) > :today')
           ->setParameter('today', new \Datetime("now"))           
           ->setParameter('farAway', new \Datetime("3100-09-09"));           

        $attributions = $qb->getQuery()->getResult();
        
        if($one && $attributions != null) return $attributions[0];
        else if(!$one && $attributions != null) return $attributions;
        else return null;
        
    }
    
    /**
     * la méthode findMembresByIds va rechercher tous les membres avec l'id
     * contenu dans l'array passé, puis les ordonner par ordre alphabétique de leur
     * nom de famille
     */
    public function findMembresByIds($ids) {
        
        $qb = $this->_em->createQueryBuilder();

        $query = $this->_em->createQuery('SELECT m FROM InterneFichierBundle:Membre m JOIN m.famille f WHERE m.id IN (?1) ORDER BY f.nom')
                      ->setParameter(1, $ids);
                      
        return $query->getResult();
    }
}
