<?php

namespace Interne\FichierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    /**
     * la méthode findCurrentAttribution va récupérer l'attribution courante
     * d'un membre
     */
    public function findCurrentAttribution($id) {
        
        $membre = $this->find($id);
        
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
           ->from('InterneStructureBundle:Attribution', 'a')
           ->where('a.membre = :membre')
           ->setParameter('membre', $membre)
           ->andWhere('a.dateFin > :today')
           ->setParameter('today', new \Datetime("now"))
           ->setMaxResults(1);

        $attributions = $qb->getQuery()->getResult();
        
        return ($attributions != null) ? $attributions[0] : null;
    }
    
    /**
     * la méthode findMembresByIds va rechercher tous les membres avec l'id
     * contenu dans l'array passé, puis les ordonner par ordre alphabétique de leur
     * nom de famille
     */
    public function findMembresByIds($ids) {
        
        $qb = $this->_em->createQueryBuilder();

        $query = $this->_em->createQuery('SELECT m FROM InterneFichierBundle:Membre m JOIN m.famille f WHERE m.id IN (?1) ORDER BY f.nom')
                      ->setParameter(1, $ids);
                      
        return $query->getResult();
    }
}
