security:
    encoders:
        Interne\SecurityBundle\Entity\User:
            algorithm: plaintext
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    
    providers:
        administrators:
            entity: { class: InterneSecurityBundle:User, property: username }


    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                
                default_target_path: /interne
                always_use_default_target_path: true
                
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/interne, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
