<?php

namespace Interne\StammBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DownloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadRepository extends EntityRepository
{
	
	/**
	 * La méthode findFullDownloads retourne la liste des téléchargements disponibles,
	 * ainsi que toutes les informations utiles pour les afficher dans le tableau
	 */
	public function findFullDownloads() {
		
		$ddls = $this->findAll();
		
		/**
		 * On récupère le type du fichier
		 */
		foreach($ddls as $ddl) {
			
			//Transformation de la taille pour affichage correct
			$size = $ddl->getSize();
			$ddl->setSize($this->formatSizeUnits($size));
			
			//On transforme ensuite la date
			$date = $ddl->getDate();
			$ddl->setDate($date->format('d.m.Y'));
			
			//On stocke le chemin absolu pour le DDL
			$abs = $ddl->getWebPath();
			$ddl->setAbsPath($abs);
		}
		
		return $ddls;
	}
	
	/**
	 * Fonction qui permet de convertir la taille d'un fichier en byte vers des Kb ou des MB
	 * de manière à l'afficher
	 */
	private function formatSizeUnits($bytes)
    {
        if ($bytes >= 1073741824)
        {
            $bytes = number_format($bytes / 1073741824, 2) . ' Gb';
        }
        elseif ($bytes >= 1048576)
        {
            $bytes = number_format($bytes / 1048576, 2) . ' Mb';
        }
        elseif ($bytes >= 1024)
        {
            $bytes = number_format($bytes / 1024, 2) . ' Kb';
        }
        elseif ($bytes > 1)
        {
            $bytes = $bytes . ' bytes';
        }
        elseif ($bytes == 1)
        {
            $bytes = $bytes . ' byte';
        }
        else
        {
            $bytes = '0 bytes';
        }

        return $bytes;
	}
}
