<?php

namespace Interne\StammBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	
	/**
	 * La méthode findNews renvoie la liste des X dernieres news
	 * en fonction de la catégorie souhaitée
	 */
	public function findNews($nbr) {
		
		$qb  = $this->createQueryBuilder('n')
					->orderBy('n.date', 'DESC')
					->setMaxResults($nbr);
		
		$news = $qb->getQuery()
				   ->getResult();
				   
		return $news;
	}
	
	/**
	 * Retourne la liste des news au format array
	 * pour json
	 */
	public function findAllNews() {
		
		
		$qb   = $this->createQueryBuilder('n')
				     ->orderBy('n.date', 'DESC');
		
		$news = $qb->getQuery()->getResult();
		
		$list = array();
		
		for($i = 0; $i < count($news); $i++) {
			
			$list[$i]['titre'] 	 = $news[$i]->getTitre();
			$list[$i]['contenu'] = $news[$i]->getContenu();
			$list[$i]['date'] 	 = $news[$i]->getDate()->format("d.m.Y");
		}
		
		return $list;
	}
}
