interne_facture_creance_add_ajax:
    path:     /add_ajax
    defaults: { _controller: InterneFactureBundle:Creance:addAjax }
    options:
            expose: true

interne_facture_creance_facturation_ajax:
    path:     /facturation_ajax
    defaults: { _controller: InterneFactureBundle:Creance:facturationAjax }
    options:
            expose: true

interne_facture_creance_waiting_liste:
    path:     /waiting_liste
    defaults: { _controller: InterneFactureBundle:Creance:waitingListe }

interne_facture_creance_add_to_liste_ajax:
    path:     /add_to_liste_ajax
    defaults: { _controller: InterneFactureBundle:Creance:addToListeAjax }
    options:
            expose: true