interne_facture_create:
    path:     /create
    defaults: { _controller: InterneFactureBundle:Facture:create }

interne_facture_show:
    path:     /show/{id}
    defaults: { _controller: InterneFactureBundle:Facture:show }

interne_facture_update:
    path:     /update/{id}
    defaults: { _controller: InterneFactureBundle:Facture:update }

interne_facture_show_all:
    path:     /showall
    defaults: { _controller: InterneFactureBundle:Facture:showAll }

interne_facture_delete:
    path:     /delete/{id}
    defaults: { _controller: InterneFactureBundle:Facture:delete }

interne_facture_search:
    path:     /search
    defaults: { _controller: InterneFactureBundle:Facture:search }

interne_facture_test:
    path:     /test
    defaults: { _controller: InterneFactureBundle:Facture:test }
