parameters:
#    interne_global.example.class: Interne\GlobalBundle\Example

services:
    global.persistor:
        class: Interne\GlobalBundle\Services\Persistor
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
            - @jms_serializer
            - @annotation_reader