parameters:
#    interne_global.example.class: Interne\GlobalBundle\Example

services:
#    interne_global.example:
#        class: %interne_global.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
