parameters:
#    externe_public.example.class: Externe\PublicBundle\Example

services:
    externe.twig_useful:
        class: Externe\PublicBundle\Services\TwigUseful
        tags:
            - { name: twig.extension }