parameters:
#    externe_public.example.class: Externe\PublicBundle\Example

services:
#    externe_public.example:
#        class: %externe_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
