<?php

namespace Interne\StructureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObtentionDistinctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObtentionDistinctionRepository extends EntityRepository
{
}
