parameters:
#    interne_home.example.class: Interne\HomeBundle\Example

services:
#    interne_home.example:
#        class: %interne_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
