<?php

namespace Externe\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitRepository extends EntityRepository
{
    /**
     * retourne le droit parent principal
     */
    public function findMainParent() {
        
        $droits = $this->findAll();
        
        for($i = 0; $i < count($droits); $i++) {
            
            if($droits[$i]->getGroupe()->getParent() == null)
                return $droits[$i];
        }
    }
    
    /**
     * retourne la liste des droits enfants au groupe passé
     * en paramètre
     */
    public function findDroitsEnfants($droit) {
        
        $enfants    = $droit->getGroupe()->getEnfants();
        $data       = array();
        
        for($i = 0; $i < count($enfants); $i++) {
            
            $droit = $this->findByGroupe($enfants[$i]);
            $droit = (empty($droit)) ? null : $droit[0];
            
            if($droit !== null && $droit->getActive()) {
                
                $data[$i]['nom']                = $droit->getGroupe()->getNom();
                $data[$i]['id']                 = $droit->getId();
                $data[$i]['color1']             = $droit->getColor1();
                $data[$i]['color2']             = $droit->getColor2();
            }
        }
        
        return $data;
    }
    
    /**
     * retourne les informations sur le droit passé en paramètre
     */
    public function findDroitData($droit) {
        
        return array(
        
            'nom'               => $droit->getGroupe()->getNom(),
            'id'                => $droit->getId(),
            'albumsVisibles'    => $droit->getAlbumsVisibles(),
            'color1'            => $droit->getColor1(),
            'color2'            => $droit->getColor2(),
        );
    }
}
